#############################################################################
# Makefile for building: final.app/Contents/MacOS/final
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  final.pro
# Template: app
# Command: /Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/qmake -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile final.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
CXX           = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
DEFINES       = -D_USE_MATH_DEFINES -DTIXML_USE_STL -DGLM_SWIZZLE -DGLM_FORCE_RADIANS -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.8 -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.8 -std=c++14 -stdlib=libc++ -g -g -std=gnu++1y -W -Waddress -Wchar-subscripts -Wformat -Wmain -Wmissing-braces -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunused-label -Wunused-variable -Wvolatile-register-var -Wno-extra -fPIC $(DEFINES)
INCPATH       = -I. -Iglm -Iui -Iglew-1.10.0/include -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/macx-g++ -F/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib
QMAKE         = /Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = final1.0.0
DISTDIR = /Users/justinzhang/Documents/Brown/Senior/CS1230/final/.tmp/final1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.8 -stdlib=libc++ -Wl,-rpath,/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ui/mainwindow.cpp \
		main.cpp \
		glew-1.10.0/src/glew.c \
		ui/view.cpp \
		ui/viewformat.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_view.cpp
OBJECTS       = mainwindow.o \
		main.o \
		glew.o \
		view.o \
		viewformat.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_view.o
DIST          = shaders/normals/normals.vert \
		shaders/normals/normals.frag \
		shaders/normals/normals.gsh \
		shaders/normals/normalsArrow.gsh \
		shaders/normals/normalsArrow.frag \
		shaders/normals/normalsArrow.vert \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/g++-base.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/g++-macx.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/macx-g++/qmake.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qml_debug.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		final.pro ui/mainwindow.h \
		ui_mainwindow.h \
		glew-1.10.0/include/GL/glew.h \
		ui/view.h \
		ui/viewformat.h ui/mainwindow.cpp \
		main.cpp \
		glew-1.10.0/src/glew.c \
		ui/view.cpp \
		ui/viewformat.cpp
QMAKE_TARGET  = final
DESTDIR       = 
TARGET        = final.app/Contents/MacOS/final


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d final.app/Contents/MacOS/ || mkdir -p final.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: final.pro /Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/macx-g++/qmake.conf /Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/g++-base.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/g++-macx.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/macx-g++/qmake.conf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qml_debug.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		final.pro \
		resources.qrc \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtXml.framework/QtXml.prl \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile final.pro
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/g++-base.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/common/g++-macx.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/macx-g++/qmake.conf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qml_debug.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/uic.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf:
final.pro:
resources.qrc:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtXml.framework/QtXml.prl:
/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile final.pro

qmake_all: FORCE

final.app/Contents/PkgInfo: 
	@test -d final.app/Contents || mkdir -p final.app/Contents
	@$(DEL_FILE) final.app/Contents/PkgInfo
	@echo "APPL????" > final.app/Contents/PkgInfo
final.app/Contents/Resources/empty.lproj: 
	@test -d final.app/Contents/Resources || mkdir -p final.app/Contents/Resources
	@touch final.app/Contents/Resources/empty.lproj
	
final.app/Contents/Info.plist: 
	@test -d final.app/Contents || mkdir -p final.app/Contents
	@$(DEL_FILE) final.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.final,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,final,g" -e "s,@LIBRARY@,final,g" -e "s,@TYPEINFO@,????,g" /Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/macx-g++/Info.plist.app >final.app/Contents/Info.plist

all: Makefile \
		final.app/Contents/PkgInfo \
		final.app/Contents/Resources/empty.lproj \
		final.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.h ui_mainwindow.h glew-1.10.0/include/GL/glew.h ui/view.h ui/viewformat.h $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.cpp main.cpp glew-1.10.0/src/glew.c ui/view.cpp ui/viewformat.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r final.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/rcc \
		shaders/shader.frag \
		shaders/shader.vert
	/Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp
moc_mainwindow.cpp: /Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui/mainwindow.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/moc
	/Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/macx-g++ -I/Users/justinzhang/Documents/Brown/Senior/CS1230/final -I/Users/justinzhang/Documents/Brown/Senior/CS1230/final/glm -I/Users/justinzhang/Documents/Brown/Senior/CS1230/final/ui -I/Users/justinzhang/Documents/Brown/Senior/CS1230/final/glew-1.10.0/include -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib ui/mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: glew-1.10.0/include/GL/glew.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		ui/view.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/moc
	/Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/mkspecs/macx-g++ -I/Users/justinzhang/Documents/Brown/Senior/CS1230/final -I/Users/justinzhang/Documents/Brown/Senior/CS1230/final/glm -I/Users/justinzhang/Documents/Brown/Senior/CS1230/final/ui -I/Users/justinzhang/Documents/Brown/Senior/CS1230/final/glew-1.10.0/include -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib ui/view.h -o moc_view.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ui/mainwindow.ui \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/uic \
		ui/view.h \
		glew-1.10.0/include/GL/glew.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h
	/Users/justinzhang/Qt5.7.1/5.7/clang_64/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: ui/mainwindow.cpp ui/mainwindow.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		ui/view.h \
		glew-1.10.0/include/GL/glew.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers/QGLFormat
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ui/mainwindow.cpp

main.o: main.cpp /Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		ui/mainwindow.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

glew.o: glew-1.10.0/src/glew.c glew-1.10.0/include/GL/glew.h \
		glew-1.10.0/include/GL/wglew.h \
		glew-1.10.0/include/GL/glxew.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glew.o glew-1.10.0/src/glew.c

view.o: ui/view.cpp ui/view.h \
		glew-1.10.0/include/GL/glew.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers/qgl.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		ui/viewformat.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers/QGLFormat \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o ui/view.cpp

viewformat.o: ui/viewformat.cpp ui/viewformat.h \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers/QGLFormat \
		/Users/justinzhang/Qt5.7.1/5.7/clang_64/lib/QtOpenGL.framework/Headers/qgl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewformat.o ui/viewformat.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

